### ISSUE TITLE
RangeError 

### ISSUE THREAD

**Issue by kevin-whiteside** [esatterwhite/eslint-plugin-sensible#14]
eslint rule throws an error when linting: `RangeError: Invalid string length`

This is the smallest repro I was able to create:

```
'use strict'

module.exports = function searchRequest(req, res) {

  async.parallel(
    async.reflect((callback) => { }),
    function (err, esResults) {
      esResults.forEach((next) => {
        if (next.value)
          meta = { ...meta, ...next.value.meta }
      })
    })
}

```

**Comment by esatterwhite** [comment]
@kevin-whiteside I'm not able to reproduce this. I'm going to need more to go on.

* Node.js Version?
* eslint version?

A stack trace would be helpful
